# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0056_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadoVariavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.TextField()),
                ('valor', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoDadosVariaveis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comercial.ContratoFechado')),
                ('proposta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comercial.PropostaComercial')),
            ],
        ),
        migrations.AddField(
            model_name='dadovariavel',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.GrupoDadosVariaveis'),
        ),
    ]
