# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0064_auto_20160228_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoFechamentoProposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='propostacomercial',
            name='substitutivo',
            field=models.BooleanField(default=False, help_text=b'Define se Proposta possui or\xc3\xa7amentos substitutivos. Nesses casos, o valor m\xc3\xadnimo ser\xc3\xa1 definido como o valor da menor proposta'),
        ),
        migrations.AddField(
            model_name='propostacomercial',
            name='definido_perdido_motivo_opcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.MotivoFechamentoProposta'),
        ),
    ]
