# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0065_auto_20160409_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgrupodocumento',
            name='apagavel',
            field=models.BooleanField(default=False),
        ),
    ]
