# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0066_itemgrupodocumento_apagavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadovariavel',
            name='tipo',
            field=models.CharField(blank=True, choices=[(b'texto', b'Texto'), (b'inteiro', 'N\xfamero  Inteiro'), (b'decimal', 'N\xfamero Decimal')], default=b'texto', max_length=100),
        ),
    ]
