# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-28 11:05
from __future__ import unicode_literals

import comercial.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0067_auto_20160607_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentogerado',
            name='arquivo_modelo',
            field=models.FileField(blank=True, upload_to=comercial.models.ArquivoModeloDir()),
        ),
    ]
