# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0069_tipodepropostadadovariavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodepropostadadovariavel',
            name='tipo_proposta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comercial.TipoDeProposta'),
            preserve_default=False,
        ),
    ]
