# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0070_tipodepropostadadovariavel_tipo_proposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodepropostadadovariavel',
            name='label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
