# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0071_tipodepropostadadovariavel_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechamentodecomissao',
            name='comissionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fechamento_comissao_set', to='rh.Funcionario', verbose_name='Respons\xe1vel Comissionado'),
        ),
    ]
