# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import sorl.thumbnail.fields
import datetime
import rh.models
from django.conf import settings
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtribuicaoDeCargo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('inicio', models.DateField(default=datetime.datetime.today)),
                ('fim', models.DateField(null=True, blank=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Criado', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualizado', auto_now=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AtribuicaoDeResponsabilidade',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('treinamento_realizado', models.BooleanField(default=False)),
                ('tipo_de_treinamento', models.CharField(blank=True, max_length=100, choices=[(b'adicionar', 'Adi\xe7\xe3o de Compet\xeancia'), (b'atualizar', 'Atualiza\xe7\xe3o de Compet\xeancia')])),
                ('horas_treinadas', models.IntegerField(null=True, blank=True)),
                ('data_treinado', models.DateField(null=True, blank=True)),
                ('confirmado_data', models.DateTimeField(null=True, blank=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AutorizacaoHoraExtra',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('quantidade', models.IntegerField()),
                ('valor_total', models.DecimalField(null=True, verbose_name='Valor Total das Horas Extra', max_digits=10, decimal_places=2, blank=True)),
                ('data_execucao', models.DateField(default=datetime.datetime.today)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
            ],
            options={
                'ordering': ['-data_execucao'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CapacitacaoDeSubProcedimento',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao_treinada', models.IntegerField(default=0, null=True, verbose_name='Vers\xe3o Treinada', blank=True)),
                ('ultima_atualizacao', models.DateField(default=datetime.datetime.today, verbose_name=b'\xc3\x9altima Atualiza\xc3\xa7\xc3\xa3o')),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cargo')),
                ('descricao', models.TextField(verbose_name='Descri\xe7\xe3o', blank=True)),
                ('salario_referencia', models.DecimalField(verbose_name='Sal\xe1rio Refer\xeancia', max_digits=10, decimal_places=2)),
                ('fracao_hora_referencia', models.DecimalField(help_text='Valor usado para calcular a participac\xe3o de funcion\xe1rio deste cargo em or\xe7amento.', verbose_name='Refer\xeancia de Fra\xe7\xe3o de Hora', max_digits=10, decimal_places=2)),
                ('periculosidade', models.DecimalField(verbose_name='Periculosidade', max_digits=10, decimal_places=2)),
                ('gratificacao', models.DecimalField(verbose_name='Gratifica\xe7\xe3o', max_digits=10, decimal_places=2)),
                ('tipo', models.CharField(default=b'escritorio', max_length=100, blank=True, choices=[(b'campo', b'Campo'), (b'escritorio', b'Escrit\xc3\xb3rio')])),
                ('dias_renovacao_exames', models.IntegerField(default=365)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Criado', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualizado', auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nome', models.CharField(max_length=100, blank=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CursoFuncionario',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nome', models.CharField(max_length=100, blank=True)),
                ('data', models.DateField(default=datetime.datetime.today, verbose_name='Data de Conclus\xe3o')),
                ('carga_horaria', models.IntegerField(null=True, verbose_name=b'Carga Hor\xc3\xa1ria', blank=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Criado', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualizado', auto_now=True)),
            ],
            options={
                'verbose_name': 'Curso Extra do Funcion\xe1rio',
                'verbose_name_plural': 'Cursos Extra dos Funcion\xe1rio',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Demissao',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('data', models.DateField(default=datetime.datetime.today)),
                ('status', models.CharField(default=b'andamento', max_length=100, blank=True, choices=[(b'andamento', b'Em Andamento'), (b'finalizado', b'Finalizado')])),
                ('termo_recisorio', models.FileField(max_length=500, null=True, upload_to=rh.models.funcionario_termo_recisorio_path, blank=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Criado', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualizado', auto_now=True)),
            ],
            options={
                'verbose_name': 'Processo de Demiss\xe3o',
                'verbose_name_plural': 'Processos de Demiss\xe3o',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nome', models.CharField(max_length=100, verbose_name=b'Nome do Departamento', blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DependenteDeFuncionario',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nome', models.CharField(max_length=100, blank=True)),
                ('relacao', models.CharField(blank=True, max_length=100, choices=[(b'f', b'Filho / Filha'), (b'p', b'Parceiro / Esposo / Esposa')])),
                ('nascimento', models.DateField(default=datetime.datetime.today)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Criado', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualizado', auto_now=True)),
            ],
            options={
                'verbose_name': 'Dependente de Funcion\xe1rio',
                'verbose_name_plural': 'Dependentes de Funcion\xe1rios',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='EntradaFolhaDePonto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('inicio', models.DateField(default=datetime.datetime.today)),
                ('fim', models.DateField(default=datetime.date.today)),
                ('total', models.DecimalField(max_digits=5, decimal_places=1)),
                ('arquivo', models.FileField(help_text=b'Arquivo a ser anexado a cada entrada', max_length=300, null=True, upload_to=rh.models.funcionario_entrada_folha_ponto_assinada, blank=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Criado', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualizado', auto_now=True)),
            ],
            options={
                'verbose_name': 'Entrada de Folha de Ponto',
                'verbose_name_plural': 'Entradas de Folha de Ponto',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ExperienciasProfissionaisFuncionario',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('emprego_atual', models.BooleanField(default=False)),
                ('nome_da_empresa', models.CharField(max_length=100, blank=True)),
                ('telefone_fixo', models.CharField(help_text=b'Formato: XX-XXXX-XXXX', max_length=100)),
                ('endereco_completo', models.TextField(blank=True)),
                ('data_admissao', models.DateField()),
                ('data_demissao', models.DateField(null=True, blank=True)),
                ('cargo_inicial', models.CharField(max_length=100, blank=True)),
                ('cargo_final', models.CharField(max_length=100, blank=True)),
                ('ultimo_salario', models.DecimalField(verbose_name='\xdaltimo Sal\xe1rio', max_digits=10, decimal_places=2)),
                ('motivo_saida', models.CharField(max_length=100, blank=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Criado', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualizado', auto_now=True)),
            ],
            options={
                'verbose_name': 'Experi\xeancia Profissional do Funcion\xe1rio',
                'verbose_name_plural': 'Experi\xeancias Profissionais do Funcion\xe1rio',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100, blank=True)),
                ('data', models.DateField()),
                ('importado_por_sync', models.BooleanField(default=False)),
                ('uid', models.CharField(max_length=100, blank=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
            ],
            options={
                'ordering': ['data'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='FolhaDePonto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('data_referencia', models.DateField(default=datetime.datetime.today, verbose_name='M\xeas e Ano de Refer\xeancia')),
                ('encerrado', models.BooleanField(default=False)),
                ('autorizado', models.BooleanField(default=False)),
                ('arquivo', models.FileField(help_text=b'Arquivo a ser anexado no fechamento do m\xc3\xaas da data de refer\xc3\xaancia', max_length=300, null=True, upload_to=rh.models.funcionario_entrada_folha_ponto_assinada, blank=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Criado', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualizado', auto_now=True)),
            ],
            options={
                'ordering': ['data_referencia'],
                'verbose_name': 'Folha de Ponto',
                'verbose_name_plural': 'Folhas de Ponto',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', django_extensions.db.fields.UUIDField(max_length=36, editable=False, blank=True)),
                ('foto', sorl.thumbnail.fields.ImageField(null=True, upload_to=rh.models.funcionario_avatar_img_path, blank=True)),
                ('nome', models.CharField(max_length=300, verbose_name='Nome do Funcion\xe1rio')),
                ('residencia', models.CharField(blank=True, max_length=100, null=True, choices=[(b'propria', b'Resid\xc3\xaancia Pr\xc3\xb3pria'), (b'aluguel', b'Resid\xc3\xaancia por Aluguel'), (b'outro', b'Outro: Casa de Parentes/Amigos')])),
                ('valor_aluguel', models.DecimalField(null=True, verbose_name='Valor do Aluguel', max_digits=10, decimal_places=2, blank=True)),
                ('nascimento', models.DateField()),
                ('observacao', models.TextField(null=True, blank=True)),
                ('sexo', models.CharField(blank=True, max_length=100, null=True, choices=[(b'm', b'Masculino'), (b'f', b'Feminino')])),
                ('naturalidade', models.CharField(max_length=100, null=True, blank=True)),
                ('nacionalidade', models.CharField(default=b'Brasil', max_length=100, null=True, blank=True)),
                ('estado_civil', models.CharField(blank=True, max_length=100, null=True, choices=[(b'casado', b'Casado'), (b'solteiro', b'Solteiro'), (b'divorciado', b'Divorciado'), (b'viuvo', b'Vi\xc3\xbavo'), (b'outros', b'Outros')])),
                ('nome_companheiro', models.CharField(max_length=300, null=True, blank=True)),
                ('nome_pai', models.CharField(max_length=300, null=True, verbose_name='Nome do Pai', blank=True)),
                ('nome_mae', models.CharField(max_length=300, null=True, verbose_name='Nome da M\xe3e', blank=True)),
                ('rg', models.CharField(max_length=100, null=True, blank=True)),
                ('rg_data', models.DateField(null=True, verbose_name='Data de Emiss\xe3o do RG', blank=True)),
                ('rg_expeditor', models.CharField(max_length=100, null=True, verbose_name='\xd3rg\xe3o Emissor do RG', blank=True)),
                ('cpf', models.CharField(max_length=255, null=True, verbose_name='CPF - Cadastro de Pessoa F\xedsica', blank=True)),
                ('carteira_profissional_numero', models.CharField(max_length=100, null=True, blank=True)),
                ('carteira_profissional_serie', models.CharField(max_length=100, null=True, blank=True)),
                ('carteira_profissional_emissao', models.DateField(null=True, blank=True)),
                ('titulo_eleitor', models.CharField(max_length=100, null=True, blank=True)),
                ('pis', models.CharField(max_length=100, null=True, blank=True)),
                ('certificado_reservista', models.CharField(max_length=100, null=True, blank=True)),
                ('carteira_habilitacao_numero', models.CharField(max_length=100, null=True, blank=True)),
                ('carteira_habilitacao_categoria', models.CharField(max_length=100, null=True, blank=True)),
                ('carteira_habilitacao_vencimento', models.DateField(null=True, blank=True)),
                ('carteira_habilitacao_expedicao', models.DateField(null=True, blank=True)),
                ('escolaridade_nivel', models.CharField(blank=True, max_length=100, null=True, choices=[(b'0', b'2\xc2\xba Grau Incompleto'), (b'1', b'2\xc2\xba Grau Completo'), (b'2', b'Ensino Superior Incompleto'), (b'3', b'Ensino Superior Completo'), (b'4', b'Ensino Superior Completo + P\xc3\xb3s Gradua\xc3\xa7\xc3\xa3o'), (b'5', b'Ensino Superior Completo + Mestrado'), (b'6', b'Ensino Superior Completo + Doutorado')])),
                ('escolaridade_cursos', models.TextField(null=True, verbose_name=b'Cursos e Institui\xc3\xa7\xc3\xb5es', blank=True)),
                ('escolaridade_serie_inconclusa', models.CharField(max_length=100, null=True, verbose_name=b'S\xc3\xa9rie m\xc3\xa1xima estudada', blank=True)),
                ('escolaridade_conclusao', models.DateField(default=datetime.datetime.today, null=True, verbose_name=b'Ano de Conclus\xc3\xa3o dos estudos', blank=True)),
                ('email', models.EmailField(max_length=75, null=True, blank=True)),
                ('telefone_fixo', models.CharField(help_text=b'Formato: XX-XXXX-XXXX', max_length=100, null=True, blank=True)),
                ('telefone_celular', models.CharField(max_length=100, null=True, blank=True)),
                ('telefone_recado', models.TextField(help_text=b'N\xc3\xbamero do telefone e contato para recados.', null=True, blank=True)),
                ('cep', models.CharField(max_length=100, null=True, verbose_name='CEP', blank=True)),
                ('rua', models.CharField(max_length=500, null=True, verbose_name='Rua', blank=True)),
                ('numero', models.CharField(max_length=100, null=True, verbose_name='N\xfamero', blank=True)),
                ('complemento', models.CharField(max_length=200, null=True, verbose_name='Complemento', blank=True)),
                ('ultima_checagem_endereco', models.DateField(default=datetime.datetime.today)),
                ('salario_inicial', models.DecimalField(null=True, verbose_name='Sal\xe1rio Inicial', max_digits=10, decimal_places=2, blank=True)),
                ('salario_atual', models.DecimalField(null=True, verbose_name='Sal\xe1rio Atual', max_digits=10, decimal_places=2, blank=True)),
                ('valor_hora', models.DecimalField(null=True, verbose_name='Valor Hora', max_digits=10, decimal_places=2, blank=True)),
                ('forma_de_pagamento', models.CharField(blank=True, max_length=100, choices=[(b'mensal', 'Pagamento Mensal')])),
                ('gratificacao', models.DecimalField(null=True, verbose_name='Gratifica\xe7\xe3o', max_digits=10, decimal_places=2, blank=True)),
                ('numero_lre', models.CharField(max_length=100, verbose_name=b'N\xc3\xbamero LRE', blank=True)),
                ('local_de_trabalho', models.TextField(blank=True)),
                ('membro_cipa', models.BooleanField(default=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Criado', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualizado', auto_now=True)),
                ('bairro', models.ForeignKey(verbose_name=b'Bairro, Cidade e Estado', to='cadastro.Bairro')),
                ('cargo_atual', models.ForeignKey(related_name=b'funcionario_cargo_atual_set', blank=True, to='rh.Cargo', null=True)),
                ('cargo_inicial', models.ForeignKey(related_name=b'funcionario_cargo_inicial_set', to='rh.Cargo')),
                ('competencias', models.ManyToManyField(to='rh.Competencia', null=True, blank=True)),
                ('endereco_empresa_designado', models.ForeignKey(default=1, verbose_name='Local de Trabalho Designado', to='cadastro.EnderecoEmpresa')),
                ('funcionario_superior', models.ForeignKey(blank=True, to='rh.Funcionario', help_text='Funcion\xe1rio a quem se reportar. Se deixado em branco, ser\xe1 usado o Grupo Respons\xe1vel pelo Departamento', null=True, verbose_name='Funcion\xe1rio Superior')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'Funcion\xe1rio',
                'verbose_name_plural': 'Funcion\xe1rios',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='GrupoDeCompetencia',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nome', models.CharField(max_length=100, blank=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='IdiomaFuncionario',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('idioma', models.CharField(blank=True, max_length=100, choices=[(b'af', b'Afrikaans'), (b'ar', b'Arabic'), (b'ast', b'Asturian'), (b'az', b'Azerbaijani'), (b'bg', b'Bulgarian'), (b'be', b'Belarusian'), (b'bn', b'Bengali'), (b'br', b'Breton'), (b'bs', b'Bosnian'), (b'ca', b'Catalan'), (b'cs', b'Czech'), (b'cy', b'Welsh'), (b'da', b'Danish'), (b'de', b'German'), (b'el', b'Greek'), (b'en', b'English'), (b'en-au', b'Australian English'), (b'en-gb', b'British English'), (b'eo', b'Esperanto'), (b'es', b'Spanish'), (b'es-ar', b'Argentinian Spanish'), (b'es-mx', b'Mexican Spanish'), (b'es-ni', b'Nicaraguan Spanish'), (b'es-ve', b'Venezuelan Spanish'), (b'et', b'Estonian'), (b'eu', b'Basque'), (b'fa', b'Persian'), (b'fi', b'Finnish'), (b'fr', b'French'), (b'fy', b'Frisian'), (b'ga', b'Irish'), (b'gl', b'Galician'), (b'he', b'Hebrew'), (b'hi', b'Hindi'), (b'hr', b'Croatian'), (b'hu', b'Hungarian'), (b'ia', b'Interlingua'), (b'id', b'Indonesian'), (b'io', b'Ido'), (b'is', b'Icelandic'), (b'it', b'Italian'), (b'ja', b'Japanese'), (b'ka', b'Georgian'), (b'kk', b'Kazakh'), (b'km', b'Khmer'), (b'kn', b'Kannada'), (b'ko', b'Korean'), (b'lb', b'Luxembourgish'), (b'lt', b'Lithuanian'), (b'lv', b'Latvian'), (b'mk', b'Macedonian'), (b'ml', b'Malayalam'), (b'mn', b'Mongolian'), (b'mr', b'Marathi'), (b'my', b'Burmese'), (b'nb', b'Norwegian Bokmal'), (b'ne', b'Nepali'), (b'nl', b'Dutch'), (b'nn', b'Norwegian Nynorsk'), (b'os', b'Ossetic'), (b'pa', b'Punjabi'), (b'pl', b'Polish'), (b'pt', b'Portuguese'), (b'pt-br', b'Brazilian Portuguese'), (b'ro', b'Romanian'), (b'ru', b'Russian'), (b'sk', b'Slovak'), (b'sl', b'Slovenian'), (b'sq', b'Albanian'), (b'sr', b'Serbian'), (b'sr-latn', b'Serbian Latin'), (b'sv', b'Swedish'), (b'sw', b'Swahili'), (b'ta', b'Tamil'), (b'te', b'Telugu'), (b'th', b'Thai'), (b'tr', b'Turkish'), (b'tt', b'Tatar'), (b'udm', b'Udmurt'), (b'uk', b'Ukrainian'), (b'ur', b'Urdu'), (b'vi', b'Vietnamese'), (b'zh-cn', b'Simplified Chinese'), (b'zh-hans', b'Simplified Chinese'), (b'zh-hant', b'Traditional Chinese'), (b'zh-tw', b'Traditional Chinese')])),
                ('nivel', models.CharField(blank=True, max_length=100, choices=[(b'0', b'B\xc3\xa1sico'), (b'1', b'Intermedi\xc3\xa1rio'), (b'2', b'Avan\xc3\xa7ado'), (b'3', b'Fluente')])),
                ('instituicao', models.CharField(max_length=100, verbose_name=b'Institui\xc3\xa7\xc3\xa3o de Ensino do Idioma', blank=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Criado', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualizado', auto_now=True)),
                ('funcionario', models.ForeignKey(to='rh.Funcionario')),
            ],
            options={
                'verbose_name': 'Idioma falado pelo Funcion\xe1rio',
                'verbose_name_plural': 'Idiomas falado pelo Funcion\xe1rio',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PerfilAcessoRH',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('gerente', models.BooleanField(default=False)),
                ('analista', models.BooleanField(default=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Criado', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualizado', auto_now=True)),
                ('user', models.OneToOneField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Acesso ao RH',
                'verbose_name_plural': 'Perfis de Acesso ao RH',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PeriodoTrabalhado',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('inicio', models.DateField(default=datetime.datetime.today)),
                ('fim', models.DateField(null=True, blank=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Criado', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualizado', auto_now=True)),
                ('funcionario', models.ForeignKey(to='rh.Funcionario')),
            ],
            options={
                'ordering': ['-criado'],
                'verbose_name': 'Per\xedodo Trabalhado',
                'verbose_name_plural': 'Per\xedodos Trabalhados',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=20, verbose_name='C\xf3digo')),
                ('nome', models.CharField(max_length=100, blank=True)),
                ('descricao', models.TextField(verbose_name='Descri\xe7\xe3o', blank=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
                ('departamento', models.ForeignKey(to='rh.Departamento')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PromocaoCargo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('avaliado', models.BooleanField(default=False)),
                ('aprovado', models.BooleanField(default=False)),
                ('observacao', models.CharField(max_length=100, verbose_name='Observa\xe7\xe3o')),
                ('data_solicitacao', models.DateField(default=datetime.datetime.today, verbose_name='Data da Solicita\xe7\xe3o de Promo\xe7\xe3o de Cargo')),
                ('data_resolucao', models.DateField(null=True, verbose_name='Data de Resolu\xe7\xe3o', blank=True)),
                ('data_promocao', models.DateField(default=datetime.datetime.today, verbose_name='Data da Efetiva\xe7\xe3o de Promo\xe7\xe3o de Cargo')),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Criado', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualizado', auto_now=True)),
                ('atribuicao_de_destino', models.OneToOneField(related_name=b'promocao_de_destino', verbose_name=b'Atribui\xc3\xa7\xc3\xa3o de Destino', to='rh.AtribuicaoDeCargo')),
                ('atribuicao_de_origem', models.OneToOneField(related_name=b'promocao_de_origem', verbose_name=b'Atribui\xc3\xa7\xc3\xa3o de Origem', to='rh.AtribuicaoDeCargo')),
                ('autorizador', models.ForeignKey(related_name=b'autorizacao_promocao_cargo_set', verbose_name='Funcion\xe1rio que Autorizou a Promo\xe7\xe3o de Cargo', blank=True, to='rh.Funcionario', null=True)),
                ('beneficiario', models.ForeignKey(related_name=b'promocao_cargo_set', verbose_name='Funcion\xe1rio Beneficiado pela Promo\xe7\xe3o de Cargo', to='rh.Funcionario')),
                ('criado_por', models.ForeignKey(related_name=b'promocaocargo_criado_set', blank=True, to='rh.Funcionario', null=True)),
                ('periodo_trabalhado', models.ForeignKey(to='rh.PeriodoTrabalhado')),
                ('solicitante', models.ForeignKey(related_name=b'solicitacao_promocao_cargo_set', verbose_name='Funcion\xe1rio Solicitante da Promo\xe7\xe3o de Cargo', to='rh.Funcionario')),
            ],
            options={
                'ordering': ['-criado'],
                'verbose_name': 'Promo\xe7\xe3o de Cargo',
                'verbose_name_plural': 'Promo\xe7\xf5es de Cargos',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PromocaoSalario',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('avaliado', models.BooleanField(default=False)),
                ('descricao', models.CharField(max_length=100, verbose_name='Descri\xe7\xe3o')),
                ('data_solicitacao', models.DateField(default=datetime.datetime.today, verbose_name='Data da Solicita\xe7\xe3o')),
                ('data_resolucao', models.DateField(null=True, verbose_name='Data de Resolu\xe7\xe3o', blank=True)),
                ('data_promocao', models.DateField(default=datetime.datetime.today, verbose_name='Data da Efetiva\xe7\xe3o de Promo\xe7\xe3o de Sal\xe1rio')),
                ('valor_origem', models.DecimalField(verbose_name='Valor de Origem', max_digits=10, decimal_places=2)),
                ('valor_destino', models.DecimalField(verbose_name='Valor de Destino', max_digits=10, decimal_places=2)),
                ('observacao', models.TextField(verbose_name='Observa\xe7\xf5es Internas', blank=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Criado', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualizado', auto_now=True)),
                ('atribuicao_de_cargo', models.ForeignKey(to='rh.AtribuicaoDeCargo')),
                ('autorizador', models.ForeignKey(related_name=b'autorizacao_promocao_salarial_set', verbose_name='Funcion\xe1rio que Autorizou a Promo\xe7\xe3o', blank=True, to='rh.Funcionario', null=True)),
                ('beneficiario', models.ForeignKey(related_name=b'promocao_salarial_set', verbose_name='Funcion\xe1rio Beneficiado', to='rh.Funcionario')),
                ('criado_por', models.ForeignKey(related_name=b'promocao_salarial_criada_set', blank=True, to='rh.Funcionario', null=True)),
                ('periodo_trabalhado', models.ForeignKey(to='rh.PeriodoTrabalhado')),
                ('solicitante', models.ForeignKey(related_name=b'solicitacao_promocao_salarial_set', verbose_name='Funcion\xe1rio Solicitante', to='rh.Funcionario')),
            ],
            options={
                'ordering': ['data_promocao'],
                'verbose_name': 'Promo\xe7\xe3o Salarial',
                'verbose_name_plural': 'Promo\xe7\xf5es Salariais',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RotinaExameMedico',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('data', models.DateTimeField(default=datetime.datetime.now, help_text=b'Formato: dd/mm/yy hh:mm', null=True, blank=True)),
                ('tipo', models.CharField(blank=True, max_length=100, choices=[(b'a', 'Admissonal'), (b'd', 'Demissonal'), (b'u', 'Peri\xf3dico'), (b'p', 'Mudan\xe7a de Fun\xe7\xe3o'), (b'r', 'Retorno ao Trabalho')])),
                ('realizado', models.BooleanField(default=False)),
                ('arquivo', models.FileField(max_length=300, null=True, upload_to=rh.models.funcionario_rotina_exame_medico, blank=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Criado', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualizado', auto_now=True)),
            ],
            options={
                'ordering': ['data'],
                'verbose_name': 'Rotina de Exame M\xe9dico',
                'verbose_name_plural': 'Rotinas de Exames M\xe9dicos',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SolicitacaoDeLicenca',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('motivo', models.TextField()),
                ('realizada', models.BooleanField(default=False)),
                ('inicio', models.DateField(default=datetime.datetime.today, verbose_name='In\xedcio da Licen\xe7a')),
                ('fim', models.DateField(default=datetime.datetime.today, verbose_name='T\xe9rmino da Licen\xe7a')),
                ('status', models.CharField(default=b'aberta', max_length=100, verbose_name='Situa\xe7\xe3o da Solicita\xe7\xe3o', choices=[(b'aberta', 'Aberta'), (b'autorizada', 'Autorizada'), (b'declinada', 'Declinada')])),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo da Solicita\xe7\xe3o', choices=[(b'ferias', 'F\xe9rias'), (b'medica', 'M\xe9dica')])),
                ('data_criado', models.DateField(default=datetime.datetime.today, verbose_name='Data da Solicita\xe7\xe3o')),
                ('data_autorizado', models.DateField(null=True, verbose_name='Data da Autoriza\xe7\xe3o', blank=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Criado', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualizado', auto_now=True)),
                ('periodo_trabalhado', models.ForeignKey(to='rh.PeriodoTrabalhado')),
                ('processado_por', models.ForeignKey(related_name=b'autorizado_por', blank=True, to='rh.Funcionario', null=True)),
            ],
            options={
                'ordering': ['inicio'],
                'verbose_name': 'Solicita\xe7\xe3o de Licen\xe7a',
                'verbose_name_plural': 'Solicita\xe7\xf5es de Licen\xe7as',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SubProcedimento',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao', models.IntegerField(default=0, verbose_name='Vers\xe3o')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(verbose_name='Descri\xe7\xe3o')),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
                ('procedimento', models.ForeignKey(to='rh.Procedimento')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TipoDeExameMedico',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nome', models.CharField(max_length=100, blank=True)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(max_digits=10, decimal_places=2)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Criado', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualizado', auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Exame M\xe9dico',
                'verbose_name_plural': 'Tipos de Exames M\xe9dicos',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='rotinaexamemedico',
            name='exames',
            field=models.ManyToManyField(to='rh.TipoDeExameMedico', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='rotinaexamemedico',
            name='periodo_trabalhado',
            field=models.ForeignKey(to='rh.PeriodoTrabalhado'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='periodo_trabalhado_corrente',
            field=models.OneToOneField(related_name=b'periodo_trabalhado_corrente', null=True, blank=True, to='rh.PeriodoTrabalhado'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='user',
            field=models.OneToOneField(null=True, blank=True, to=settings.AUTH_USER_MODEL, verbose_name=b'Usu\xc3\xa1rio do Sistema'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='folhadeponto',
            name='funcionario_autorizador',
            field=models.ForeignKey(related_name=b'folhadeponto_autorizado_set', blank=True, to='rh.Funcionario', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='folhadeponto',
            name='periodo_trabalhado',
            field=models.ForeignKey(to='rh.PeriodoTrabalhado'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='experienciasprofissionaisfuncionario',
            name='funcionario',
            field=models.ForeignKey(to='rh.Funcionario'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='entradafolhadeponto',
            name='adicionado_por',
            field=models.ForeignKey(related_name=b'entradas_folha_lancada_set', to='rh.Funcionario'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='entradafolhadeponto',
            name='folha',
            field=models.ForeignKey(to='rh.FolhaDePonto'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dependentedefuncionario',
            name='funcionario',
            field=models.ForeignKey(to='rh.Funcionario'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='demissao',
            name='demissor',
            field=models.ForeignKey(related_name=b'demissor_set', to='rh.Funcionario'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='demissao',
            name='demitido',
            field=models.ForeignKey(related_name=b'demissao_set', to='rh.Funcionario'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='demissao',
            name='periodo_trabalhado_finalizado',
            field=models.ForeignKey(to='rh.PeriodoTrabalhado'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cursofuncionario',
            name='funcionario',
            field=models.ForeignKey(to='rh.Funcionario'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='competencia',
            name='grupo',
            field=models.ForeignKey(to='rh.GrupoDeCompetencia'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cargo',
            name='competencias',
            field=models.ManyToManyField(to='rh.Competencia'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cargo',
            name='departamento',
            field=models.ForeignKey(to='rh.Departamento'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cargo',
            name='exame_medico_padrao',
            field=models.ManyToManyField(to='rh.TipoDeExameMedico'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cargo',
            name='subprocedimentos',
            field=models.ManyToManyField(to='rh.SubProcedimento'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='capacitacaodesubprocedimento',
            name='periodo_trabalhado',
            field=models.ForeignKey(verbose_name=b'Per\xc3\xadodo Trabalhado', to='rh.PeriodoTrabalhado'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='capacitacaodesubprocedimento',
            name='subprocedimento',
            field=models.ForeignKey(to='rh.SubProcedimento'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='autorizacaohoraextra',
            name='periodo_trabalhado',
            field=models.ForeignKey(to='rh.PeriodoTrabalhado'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='autorizacaohoraextra',
            name='solicitante',
            field=models.ForeignKey(related_name=b'solicitante_horaextra_set', to='rh.Funcionario'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='atribuicaoderesponsabilidade',
            name='confirmado_por',
            field=models.ForeignKey(related_name=b'atribuicaoderesponsabilidade_confirmado_set', blank=True, to='rh.Funcionario', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='atribuicaoderesponsabilidade',
            name='criado_por',
            field=models.ForeignKey(related_name=b'atribuicaoderesponsabilidade_criado_set', to='rh.Funcionario'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='atribuicaoderesponsabilidade',
            name='periodo_trabalhado',
            field=models.ForeignKey(to='rh.PeriodoTrabalhado'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='atribuicaoderesponsabilidade',
            name='subprocedimentos',
            field=models.ManyToManyField(to='rh.SubProcedimento'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='atribuicaodecargo',
            name='cargo',
            field=models.ForeignKey(to='rh.Cargo'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='atribuicaodecargo',
            name='criado_por',
            field=models.ForeignKey(related_name=b'atribuicaodecargo_criado_set', blank=True, to='rh.Funcionario', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='atribuicaodecargo',
            name='local_empresa',
            field=models.ForeignKey(default=1, verbose_name='Local designado', to='cadastro.EnderecoEmpresa'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='atribuicaodecargo',
            name='periodo_trabalhado',
            field=models.ForeignKey(to='rh.PeriodoTrabalhado'),
            preserve_default=True,
        ),
    ]
