# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaValores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_placas_inicial', models.IntegerField(blank=True, null=True)),
                ('quantidade_placas_final', models.IntegerField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Contrato')),
            ],
        ),
    ]
