# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financiamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelaFinanciamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade de Parcelas')),
                ('juros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
            ],
        ),
        migrations.CreateModel(
            name='PorteFinanciamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('financiamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retscreen.Financiamento')),
            ],
        ),
        migrations.CreateModel(
            name='TabelaValores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_placas_inicial', models.IntegerField(blank=True, null=True)),
                ('quantidade_placas_final', models.IntegerField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Contrato')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
            ],
        ),
        migrations.AddField(
            model_name='parcelafinanciamento',
            name='porte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retscreen.PorteFinanciamento'),
        ),
    ]
