# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retscreen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelavalores',
            name='quantidade_placas_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tabelavalores',
            name='quantidade_placas_inicial',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
