# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0065_auto_20160409_1702'),
        ('retscreen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaParcelamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('juros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Contrato')),
                ('parcelas', models.IntegerField(blank=True, null=True)),
                ('empresas', models.ManyToManyField(to='comercial.EmpresaComercial')),
            ],
        ),
    ]
