# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-29 20:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('retscreen', '0002_formaparcelamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financiamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelaFinanciamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('juros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
            ],
        ),
        migrations.CreateModel(
            name='PorteFinanciamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('parcelamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retscreen.Financiamento')),
            ],
        ),
        migrations.RemoveField(
            model_name='formaparcelamento',
            name='empresas',
        ),
        migrations.AddField(
            model_name='tabelavalores',
            name='atualizado',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 29, 20, 38, 54, 923419, tzinfo=utc), verbose_name='Atualizado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabelavalores',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 29, 20, 38, 59, 879536, tzinfo=utc), verbose_name='Criado'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FormaParcelamento',
        ),
        migrations.AddField(
            model_name='parcelafinanciamento',
            name='porte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retscreen.PorteFinanciamento'),
        ),
    ]
