# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-29 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retscreen', '0003_auto_20160529_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portefinanciamento',
            old_name='parcelamento',
            new_name='financiamento',
        ),
    ]
