# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retscreen', '0003_reajusteenergiaano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reajusteenergiaano',
            name='ano',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
