# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0071_tipodepropostadadovariavel_label'),
        ('retscreen', '0004_auto_20160906_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelavalores',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabelas_retscreen', to='comercial.EmpresaComercial'),
        ),
    ]
