# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-29 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retscreen', '0004_auto_20160529_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelafinanciamento',
            name='quantidade',
            field=models.IntegerField(default=1, verbose_name='Quantidade de Parcelas'),
            preserve_default=False,
        ),
    ]
