# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_auto_20151023_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='precliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='precliente',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
