# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import datetime
import django.db.models.deletion
import producao.models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoAnexoComponente',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('arquivo', models.FileField(upload_to=producao.models.anexo_componente_local)),
                ('nome', models.CharField(max_length=100)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
            ],
            options={
                'ordering': ('criado',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AtividadeDeCompra',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('data', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Data')),
                ('descricao', models.TextField(verbose_name='Descri\xe7\xe3o')),
                ('data_fechado', models.DateTimeField(null=True, blank=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
            ],
            options={
                'ordering': ('data',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ativo', models.BooleanField(default=True)),
                ('imagem', models.ImageField(null=True, upload_to=producao.models.componente_local_imagem, blank=True)),
                ('part_number', models.CharField(help_text=b'IDENTIFICADOR GERADO AUTOM\xc3\x81TICO', max_length=100, null=True, verbose_name=b'PART NUMBER', blank=True)),
                ('identificador', models.IntegerField(default=1, null=True, verbose_name=b'Identificador \xc3\xbanico junto a categoria', blank=True)),
                ('descricao', models.TextField(verbose_name=b'Descri\xc3\xa7\xc3\xa3o', blank=True)),
                ('nacionalidade', models.CharField(max_length=1, choices=[(b'n', b'Nacional'), (b'i', b'Internacional')])),
                ('ncm', models.CharField(max_length=100, verbose_name=b'NCM', blank=True)),
                ('lead_time', models.IntegerField(verbose_name=b'Lead Time (Semanas)')),
                ('preco_liquido_unitario_dolar', models.DecimalField(default=0, help_text=b'INSERIDO AUTOMATICAMENTE DA ULTIMA COMPRA', verbose_name=b'Pre\xc3\xa7o L\xc3\xadquido Unit\xc3\xa1rio em D\xc3\xb3lar', max_digits=10, decimal_places=2)),
                ('preco_liquido_unitario_real', models.DecimalField(default=0, help_text=b'INSERIDO AUTOMATICAMENTE DA ULTIMA COMPRA', verbose_name=b'Pre\xc3\xa7o L\xc3\xadquido Unit\xc3\xa1rio em Real', max_digits=10, decimal_places=2)),
                ('preco_medio_unitario', models.DecimalField(default=0, verbose_name=b'Pre\xc3\xa7o M\xc3\xa9dio Bruto Unit\xc3\xa1rio', max_digits=10, decimal_places=2)),
                ('medida', models.CharField(default=b'un', max_length=100, blank=True, choices=[(b'und', b'Unidade'), (b'm', b'Metro')])),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
            ],
            options={
                'ordering': ('part_number',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ComponenteTipo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('slug', models.SlugField(help_text='Abrevia\xe7\xe3o para diret\xf3rios e urls', unique=True, max_length=3, verbose_name='Abrevia\xe7\xe3o')),
                ('nome', models.CharField(unique=True, max_length=100, verbose_name='Descri\xe7\xe3o')),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ControleDeCompra',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titulo', models.CharField(max_length=100, verbose_name='T\xedtulo', blank=True)),
                ('data_aberto', models.DateField(default=datetime.datetime.today, blank=True)),
                ('data_fechado', models.DateField(null=True, verbose_name=b'Data de Fechamento', blank=True)),
                ('descricao', models.TextField(verbose_name='Descri\xe7\xe3o')),
                ('criticidade', models.IntegerField(default=0, max_length=1, choices=[(0, b'Baixa'), (1, b'M\xc3\xa9dia'), (2, b'Urgente')])),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
            ],
            options={
                'ordering': ['-criado'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DocumentoTecnicoProduto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('arquivo', models.FileField(upload_to=producao.models.produto_local_documentos)),
                ('nome', models.CharField(max_length=100)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento T\xe9cnico do Sub Produto',
                'verbose_name_plural': 'Documentos T\xe9cnicos do Sub Produto',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DocumentoTecnicoSubProduto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nome', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to=producao.models.subproduto_local_documentos)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento T\xe9cnico do Sub Produto',
                'verbose_name_plural': 'Documentos T\xe9cnicos do Sub Produto',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='EstoqueFisico',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100, blank=True)),
                ('identificacao', models.SlugField(help_text='Abrevia\xe7\xe3o para diret\xf3rios e urls', verbose_name='Abrevia\xe7\xe3o')),
                ('local_fisico', models.TextField(null=True, blank=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='FabricanteFornecedor',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tipo', models.CharField(blank=True, max_length=100, choices=[(b'fabricante', b'Fabricante'), (b'fornecedor', b'Fornecedor')])),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Raz\xe3o Social')),
                ('cnpj', models.CharField(max_length=400, verbose_name=b'CNPJ', blank=True)),
                ('contatos', models.TextField(blank=True)),
                ('rua', models.CharField(max_length=100, blank=True)),
                ('numero', models.CharField(max_length=100, blank=True)),
                ('bairro', models.CharField(max_length=100, blank=True)),
                ('cep', models.CharField(max_length=100, verbose_name=b'CEP', blank=True)),
                ('cidade', models.CharField(max_length=100, blank=True)),
                ('estado', models.CharField(max_length=100, blank=True)),
                ('telefone', models.CharField(max_length=100, blank=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='FalhaDeTeste',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tipo', models.CharField(default=b'perda', max_length=100, choices=[(b'perda', b'Falha com Perda'), (b'reparo', b'Falha com Reparo')])),
                ('codigo', models.CharField(max_length=100, verbose_name=b'C\xc3\xb3digo')),
                ('descricao', models.TextField(verbose_name='Descri\xe7\xe3o')),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ['-criado'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='FollowUpRequisicaoCompra',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('texto', models.TextField()),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Criado', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualizado', auto_now=True)),
                ('criado_por', models.ForeignKey(related_name=b'followup_requisicao_adicionado_set', to='rh.Funcionario')),
            ],
            options={
                'ordering': ['-criado'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='LancamentoComponente',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('peso', models.IntegerField(null=True, blank=True)),
                ('part_number_fornecedor', models.CharField(max_length=100, verbose_name=b'Part Number Fornecedor', blank=True)),
                ('quantidade', models.DecimalField(max_digits=15, decimal_places=2)),
                ('valor_unitario', models.DecimalField(default=0, verbose_name=b'Valor Unit\xc3\xa1rio (R$)', max_digits=10, decimal_places=2)),
                ('impostos', models.DecimalField(default=0, help_text='Incid\xeancia total de impostos deste Lan\xe7amento em (%)', verbose_name=b'Incid\xc3\xaancia de Impostos (%)', max_digits=10, decimal_places=2)),
                ('part_number_fabricante', models.CharField(max_length=100, verbose_name=b'Part Number Fabricante', blank=True)),
                ('aprender', models.BooleanField(default=False)),
                ('valor_total_sem_imposto', models.DecimalField(default=0, help_text=b'Campo calculado automaticamente', verbose_name=b'Total do Lan\xc3\xa7amento sem Imposto', max_digits=10, decimal_places=2)),
                ('valor_total_com_imposto', models.DecimalField(default=0, help_text=b'Campo calculado automaticamente', verbose_name=b'Total do Lan\xc3\xa7amento com Imposto', max_digits=10, decimal_places=2)),
                ('valor_taxa_diversa_proporcional', models.DecimalField(default=0, help_text=b'Campo calculado automaticamente', verbose_name=b'Valor proporcional da Taxa Diversa da Nota', max_digits=10, decimal_places=2)),
                ('valor_unitario_final', models.DecimalField(default=0, help_text=b'Campo calculado automaticamente', verbose_name=b'Valor Unit\xc3\xa1rio Bruto', max_digits=10, decimal_places=2)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
                ('componente', models.ForeignKey(verbose_name=b'PART NUMBER', blank=True, to='producao.Componente', null=True)),
                ('fabricante', models.ForeignKey(blank=True, to='producao.FabricanteFornecedor', null=True)),
            ],
            options={
                'ordering': ('peso', 'nota'),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='LancamentoDeFalhaDeTeste',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('quantidade_total_testada', models.IntegerField(default=0)),
                ('quantidade_funcional_direta', models.IntegerField(default=0)),
                ('quantidade_perdida', models.IntegerField(default=0)),
                ('quantidade_reparada_funcional', models.IntegerField(default=0)),
                ('quantidade_funcional', models.IntegerField(default=0)),
                ('data_lancamento', models.DateField(default=datetime.datetime.today, verbose_name='Data de Lan\xe7amento')),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('funcionario_testador', models.ForeignKey(verbose_name='Funcion\xe1rio Testador', to='rh.Funcionario')),
            ],
            options={
                'ordering': ['-criado'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='LancamentoProdProduto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('serial_number', models.CharField(default=None, max_length=100, null=True)),
                ('data_montagem', models.DateField(default=datetime.datetime.today, null=True, verbose_name=b'Data de Montagem', blank=True)),
                ('inicio_teste', models.DateField(default=datetime.datetime.today, null=True, verbose_name=b'In\xc3\xadcio de Teste', blank=True)),
                ('realizacao_procedimento_de_teste', models.DateField(default=datetime.datetime.today, null=True, verbose_name='Realiza\xe7\xe3o de Procedimento de Teste', blank=True)),
                ('fim_teste', models.DateField(default=datetime.datetime.today, null=True, verbose_name=b'Fim de Teste', blank=True)),
                ('cliente_associado', models.CharField(max_length=100, null=True, blank=True)),
                ('observacoes', models.TextField(verbose_name='Observa\xe7\xf5es', blank=True)),
                ('adicionado_manualmente', models.BooleanField(default=True)),
                ('justificativa_adicionado', models.TextField(blank=True)),
                ('apagado', models.BooleanField(default=False)),
                ('justificativa_apagado', models.TextField(blank=True)),
                ('data_apagado', models.DateTimeField(default=None, null=True, blank=True)),
                ('vendido', models.BooleanField(default=False)),
                ('data_vendido', models.DateTimeField(default=None, null=True, blank=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
                ('funcionario_adicionou', models.ForeignKey(related_name=b'lancamento_de_producao_produto_adicionado_set', blank=True, to='rh.Funcionario', null=True)),
                ('funcionario_apagou', models.ForeignKey(related_name=b'lancamento_de_producao_produto_apagado_set', blank=True, to='rh.Funcionario', null=True)),
                ('funcionario_finalizou_teste', models.ForeignKey(related_name=b'lancamento_de_producao_produto_teste_finalizado_set', verbose_name='Funcion\xe1rio que finalizou o teste', blank=True, to='rh.Funcionario', null=True)),
                ('funcionario_inicio_teste', models.ForeignKey(related_name=b'lancamento_de_producao_produto_teste_iniciado_set', verbose_name='Funcion\xe1rio que iniciou o teste', blank=True, to='rh.Funcionario', null=True)),
                ('funcionario_que_montou', models.ForeignKey(related_name=b'lancamento_de_producao_produto_montado_set', verbose_name='Funcion\xe1rio que montou', blank=True, to='rh.Funcionario', null=True)),
                ('funcionario_relalizou_teste', models.ForeignKey(related_name=b'lancamento_de_producao_produto_teste_realizado_set', verbose_name='Funcion\xe1rio que realizou o teste', blank=True, to='rh.Funcionario', null=True)),
                ('funcionario_vendeu', models.ForeignKey(related_name=b'lancamento_de_producao_produto_vendido_set', blank=True, to='rh.Funcionario', null=True)),
            ],
            options={
                'ordering': ['-criado'],
                'verbose_name': 'Lan\xe7amento de Produ\xe7\xe3o de Produto',
                'verbose_name_plural': 'Lan\xe7amentos de Produ\xe7\xe3o de Produto',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='LinhaComponenteAvulsodoProduto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('quantidade', models.DecimalField(default=1, max_digits=10, decimal_places=2)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
                ('componente', models.ForeignKey(to='producao.Componente')),
            ],
            options={
                'verbose_name': 'Linha de Componente Avulso do Produto',
                'verbose_name_plural': 'Linhas de Componentes Avulsos do Produto',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='LinhaFornecedorFabricanteComponente',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('part_number_fornecedor', models.CharField(max_length=100, blank=True)),
                ('part_number_fabricante', models.CharField(max_length=100, null=True, blank=True)),
                ('componente', models.ForeignKey(to='producao.Componente')),
                ('fabricante', models.ForeignKey(related_name=b'fabricante_componente_set', blank=True, to='producao.FabricanteFornecedor', null=True)),
                ('fornecedor', models.ForeignKey(related_name=b'fornecedor_componente_set', to='producao.FabricanteFornecedor')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='LinhaLancamentoFalhaDeTeste',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('quantidade', models.IntegerField()),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
                ('falha', models.ForeignKey(to='producao.FalhaDeTeste')),
                ('lancamento_teste', models.ForeignKey(to='producao.LancamentoDeFalhaDeTeste')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='LinhaSubProduto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('peso', models.IntegerField(null=True, verbose_name=b'Item', blank=True)),
                ('tag', models.CharField(max_length=100, verbose_name=b'TAG', blank=True)),
                ('valor_custo_da_linha', models.DecimalField(default=0, max_digits=10, decimal_places=2)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
            ],
            options={
                'ordering': ('tag',),
                'verbose_name': 'Linha de Componentes do Sub Produto',
                'verbose_name_plural': 'Linhas de Componentes do Sub Produto',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='LinhaSubProdutoAgregado',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('quantidade', models.IntegerField(default=1, help_text='N\xfamero Inteiro', null=True, blank=True)),
            ],
            options={
                'verbose_name': 'Linha Sub Produto Agregado',
                'verbose_name_plural': 'Linha de Sub Produtos Agregados',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='LinhaSubProdutodoProduto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('quantidade', models.IntegerField(default=1)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
            ],
            options={
                'ordering': ('-criado', '-id'),
                'verbose_name': 'Linha de Sub Produto do Produto',
                'verbose_name_plural': 'Linhas Sub Produto do Produto',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='LinhaTesteLancamentoProdProduto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('versao_firmware', models.CharField(max_length=100, verbose_name='Vers\xe3o do Firmware', blank=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
                ('funcionario_que_montou', models.ForeignKey(related_name=b'linha_de_montagem_de_lancamento_de_produto_set', blank=True, to='rh.Funcionario', null=True)),
                ('funcionario_que_testou', models.ForeignKey(related_name=b'linha_de_teste_de_lancamento_de_produto_set', blank=True, to='rh.Funcionario', null=True)),
                ('lancamento_de_producao', models.ForeignKey(verbose_name='Lan\xe7amento de Produ\xe7\xe3o do Produto', to='producao.LancamentoProdProduto')),
            ],
            options={
                'ordering': ['-criado'],
                'verbose_name': 'Teste de Lan\xe7amento de Produto Produzido',
                'verbose_name_plural': 'Testes do Lan\xe7amento de Produto Produzido',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MovimentoEstoqueProduto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('operacao', models.CharField(default=b'adiciona', max_length=100, blank=True, choices=[(b'adiciona', b'Adiciona'), (b'remove', b'Remove')])),
                ('quantidade_movimentada', models.IntegerField()),
                ('quantidade_anterior', models.IntegerField()),
                ('quantidade_nova', models.IntegerField()),
                ('justificativa', models.TextField()),
                ('criado_manualmente', models.BooleanField(default=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ['-criado'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MovimentoEstoqueSubProduto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('situacao', models.CharField(default=0, max_length=100, choices=[(b'0', b'Montado'), (b'1', b'Em Teste'), (b'2', b'Funcional')])),
                ('operacao', models.CharField(default=b'adiciona', max_length=100, choices=[(b'adiciona', b'Adiciona'), (b'remove', b'Remove')])),
                ('quantidade_movimentada', models.IntegerField()),
                ('quantidade_anterior', models.IntegerField()),
                ('quantidade_nova', models.IntegerField()),
                ('justificativa', models.TextField()),
                ('criado_manualmente', models.BooleanField(default=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ['-criado'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('numero', models.CharField(max_length=100, verbose_name=b'N\xc3\xbamero')),
                ('serie', models.CharField(max_length=100, null=True, verbose_name=b'S\xc3\xa9rie / Tipo de Nota', blank=True)),
                ('tipo', models.CharField(max_length=1, choices=[(b'n', b'Nacional'), (b'i', b'Internacional')])),
                ('taxas_diversas', models.DecimalField(decimal_places=2, default=0, max_digits=10, blank=True, null=True, verbose_name=b'Valores Diversos (R$)')),
                ('cotacao_dolar', models.DecimalField(decimal_places=2, max_digits=10, blank=True, help_text=b'utilizado somente em notas Internacionais', null=True, verbose_name=b'Cota\xc3\xa7\xc3\xa3o do Dolar em Rela\xc3\xa7\xc3\xa3o ao Real (R$)')),
                ('status', models.CharField(default=b'a', max_length=100, blank=True, choices=[(b'a', b'Aberta'), (b'l', b'Lan\xc3\xa7ada')])),
                ('data_entrada', models.DateTimeField(default=datetime.datetime.now, blank=True)),
                ('data_lancado_estoque', models.DateTimeField(null=True, blank=True)),
                ('total_sem_imposto', models.DecimalField(decimal_places=2, default=0, max_digits=10, blank=True, help_text=b'Campo calculado automaticamente', null=True, verbose_name=b'Total da Nota sem Imposto')),
                ('total_com_imposto', models.DecimalField(decimal_places=2, default=0, max_digits=10, blank=True, help_text=b'Campo calculado automaticamente', null=True, verbose_name=b'Total da Nota com Imposto')),
                ('total_da_nota_em_dolar', models.DecimalField(decimal_places=2, default=0, max_digits=10, blank=True, help_text=b'Campo calculado automaticamente', null=True, verbose_name=b'Total da Nota em Dolar')),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
                ('fabricante_fornecedor', models.ForeignKey(verbose_name=b'Fornecedor', to='producao.FabricanteFornecedor')),
                ('lancado_por', models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ['-criado'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='NotaFiscalLancamentosProducao',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('notafiscal', models.CharField(max_length=100, verbose_name=b'Nota Fiscal SELTEC')),
                ('cliente_associado', models.CharField(max_length=100)),
                ('data_saida', models.DateField(default=datetime.datetime.today, verbose_name=b'Data de Sa\xc3\xadda')),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('lancamentos_de_producao', models.ManyToManyField(to='producao.LancamentoProdProduto', verbose_name='Lan\xe7amentos de Produ\xe7\xe3o')),
            ],
            options={
                'ordering': ['-criado'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='OpcaoLinhaSubProduto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('quantidade', models.DecimalField(max_digits=10, decimal_places=2)),
                ('padrao', models.NullBooleanField(default=False, verbose_name='Padr\xe3o')),
                ('componente', models.ForeignKey(to='producao.Componente')),
                ('linha', models.ForeignKey(to='producao.LinhaSubProduto')),
            ],
            options={
                'ordering': ('-padrao',),
                'verbose_name': 'Op\xe7\xe3o para a Linha do SubProduto',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='OrdemConversaoSubProduto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('quantidade', models.IntegerField()),
                ('string_producao', models.TextField()),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='OrdemProducaoProduto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('quantidade', models.IntegerField()),
                ('string_producao', models.TextField()),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ['-criado'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='OrdemProducaoSubProduto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('quantidade', models.IntegerField()),
                ('string_producao', models.TextField()),
                ('data_producao', models.DateField(default=datetime.datetime.today)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('funcionario_produtor', models.ForeignKey(verbose_name='Funcion\xe1rio Produtor', to='rh.Funcionario')),
            ],
            options={
                'ordering': ['-criado'],
                'verbose_name': 'Ordem de Produ\xe7\xe3o do Sub Produto',
                'verbose_name_plural': 'Ordens de Produ\xe7\xe3o do Sub Produto',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PerfilAcessoProducao',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('gerente', models.BooleanField(default=False)),
                ('gerente_de_compras', models.BooleanField(default=False)),
                ('analista', models.BooleanField(default=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Criado', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualizado', auto_now=True)),
                ('user', models.OneToOneField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Acesso \xe0 Produ\xe7\xe3o',
                'verbose_name_plural': 'Perfis de Acesso \xe0 Produ\xe7\xe3o',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PosicaoEstoque',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('data_entrada', models.DateTimeField(default=datetime.datetime.now, blank=True)),
                ('quantidade', models.DecimalField(max_digits=15, decimal_places=2)),
                ('quantidade_alterada', models.TextField(blank=True)),
                ('justificativa', models.TextField(blank=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
                ('componente', models.ForeignKey(to='producao.Componente')),
                ('criado_por', models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('estoque', models.ForeignKey(to='producao.EstoqueFisico')),
                ('nota_referencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, blank=True, to='producao.NotaFiscal', null=True)),
                ('ordem_producao_conversao_subproduto_referencia', models.ForeignKey(blank=True, to='producao.OrdemConversaoSubProduto', null=True)),
                ('ordem_producao_produto_referencia', models.ForeignKey(blank=True, to='producao.OrdemProducaoProduto', null=True)),
                ('ordem_producao_subproduto_referencia', models.ForeignKey(blank=True, to='producao.OrdemProducaoSubProduto', null=True)),
            ],
            options={
                'ordering': ('-criado', '-id'),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ProdutoFinal',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ativo', models.BooleanField(default=True)),
                ('imagem', models.ImageField(null=True, upload_to=producao.models.subproduto_local_imagem, blank=True)),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(null=True, blank=True, help_text='Abrevia\xe7\xe3o para diret\xf3rios e urls', unique=True, verbose_name='Abrevia\xe7\xe3o')),
                ('part_number', models.CharField(max_length=100, blank=True)),
                ('descricao', models.TextField(verbose_name='Descri\xe7\xe3o', blank=True)),
                ('total_produzido', models.IntegerField(default=0)),
                ('quantidade_estimada_producao_semanal', models.IntegerField(verbose_name='Quantidade Estimada de Produ\xe7\xe3o Semanal')),
                ('quantidade_maxima_estocavel', models.IntegerField(null=True, verbose_name='Quantidade M\xe1xima de Produto Estoc\xe1vel')),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
            ],
            options={
                'ordering': ('part_number',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RegistroEnvioDeTesteSubProduto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('quantidade', models.IntegerField()),
                ('data_envio', models.DateTimeField(default=datetime.datetime.now)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('funcionario', models.ForeignKey(to='rh.Funcionario')),
            ],
            options={
                'ordering': ['-criado'],
                'verbose_name': 'Registro de Envio de Testes do Sub Produto',
                'verbose_name_plural': 'Registros de Envio de Testes do Sub Produto',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RegistroSaidaDeTesteSubProduto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('quantidade', models.IntegerField()),
                ('data_envio', models.DateTimeField(default=datetime.datetime.now)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('funcionario', models.ForeignKey(to='rh.Funcionario')),
            ],
            options={
                'ordering': ['-criado'],
                'verbose_name': 'Registro de Sa\xedda de Testes do Sub Produto',
                'verbose_name_plural': 'Registros de Sa\xedda de Testes do Sub Produto',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RegistroValorEstoque',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('data', models.DateTimeField(default=datetime.datetime.now, blank=True)),
                ('valor', models.DecimalField(default=0, help_text=b'Valor total do Estoque', verbose_name=b'Valor do Estoque', max_digits=20, decimal_places=2)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
            ],
            options={
                'ordering': ('data',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RequisicaoDeCompra',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('atendido', models.BooleanField(default=False)),
                ('atendido_em', models.DateTimeField(default=datetime.datetime.now, blank=True)),
                ('inicio_atendimento', models.DateTimeField(default=datetime.datetime.now, blank=True)),
                ('data_solicitado', models.DateField(default=datetime.datetime.today, verbose_name='Data para Atender')),
                ('descricao', models.TextField(verbose_name='Descri\xe7\xe3o')),
                ('criticidade', models.IntegerField(default=0, max_length=1, choices=[(0, b'Baixa'), (1, b'M\xc3\xa9dia'), (2, b'Urgente')])),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
                ('solicitado', models.ForeignKey(related_name=b'requisicao_de_compra_requerida', verbose_name=b'Funcion\xc3\xa1rio Solicitante', to='rh.Funcionario')),
                ('solicitante', models.ForeignKey(related_name=b'requisicao_de_compra_solicitada', to='rh.Funcionario')),
            ],
            options={
                'ordering': ['-criado'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SubProduto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ativo', models.BooleanField(default=True)),
                ('imagem', models.ImageField(null=True, upload_to=producao.models.subproduto_local_imagem, blank=True)),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(null=True, blank=True, help_text='Abrevia\xe7\xe3o para diret\xf3rios e urls', unique=True, verbose_name='Abrevia\xe7\xe3o')),
                ('part_number', models.CharField(max_length=100, blank=True)),
                ('descricao', models.TextField(verbose_name='Descri\xe7\xe3o', blank=True)),
                ('possui_tags', models.BooleanField(default=True, help_text=b'Se este campo for marcado, as Linhas do Sub Produto dever\xc3\xa3o ser alocadas para uma TAG \xc3\xbanica.')),
                ('tipo_de_teste', models.IntegerField(default=0, choices=[(0, 'Nulo'), (1, b'Simples'), (2, b'Composto')])),
                ('total_montado', models.IntegerField(default=0)),
                ('total_testando', models.IntegerField(default=0)),
                ('total_funcional', models.IntegerField(default=0)),
                ('valor_total_de_custo', models.DecimalField(max_digits=10, decimal_places=2)),
                ('valor_custo_total_linhas', models.DecimalField(max_digits=10, decimal_places=2)),
                ('valor_custo_total_dos_sub_produtos_agregados', models.DecimalField(max_digits=10, decimal_places=2)),
                ('notacao_de_producao', models.TextField(default=b'{}', blank=True)),
                ('criado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Cria\xc3\xa7\xc3\xa3o', auto_now_add=True)),
                ('atualizado', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Atualiza\xc3\xa7\xc3\xa3o', auto_now=True)),
            ],
            options={
                'ordering': ('part_number',),
                'verbose_name': 'Sub Produto',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='registrosaidadetestesubproduto',
            name='subproduto',
            field=models.ForeignKey(to='producao.SubProduto'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='registroenviodetestesubproduto',
            name='subproduto',
            field=models.ForeignKey(to='producao.SubProduto'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='produtofinal',
            name='subprodutos_testaveis',
            field=models.ManyToManyField(to='producao.SubProduto', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ordemproducaosubproduto',
            name='subproduto',
            field=models.ForeignKey(to='producao.SubProduto'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ordemproducaoproduto',
            name='produto',
            field=models.ForeignKey(to='producao.ProdutoFinal'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ordemconversaosubproduto',
            name='subproduto_destino',
            field=models.ForeignKey(related_name=b'ordem_conversao_subproduto_destino_set', to='producao.SubProduto'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ordemconversaosubproduto',
            name='subproduto_original',
            field=models.ForeignKey(related_name=b'ordem_conversao_subproduto_original_set', to='producao.SubProduto'),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name='opcaolinhasubproduto',
            unique_together=set([('linha', 'padrao')]),
        ),
        migrations.AlterUniqueTogether(
            name='notafiscal',
            unique_together=set([('fabricante_fornecedor', 'numero')]),
        ),
        migrations.AddField(
            model_name='movimentoestoquesubproduto',
            name='ordem_de_producao',
            field=models.ForeignKey(blank=True, to='producao.OrdemProducaoSubProduto', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='movimentoestoquesubproduto',
            name='subproduto',
            field=models.ForeignKey(to='producao.SubProduto'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='movimentoestoqueproduto',
            name='ordem_de_producao',
            field=models.ForeignKey(blank=True, to='producao.OrdemProducaoProduto', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='movimentoestoqueproduto',
            name='produto',
            field=models.ForeignKey(to='producao.ProdutoFinal'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='movimentoestoqueproduto',
            name='registro_de_nota_fiscal',
            field=models.ForeignKey(blank=True, to='producao.NotaFiscalLancamentosProducao', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='linhatestelancamentoprodproduto',
            name='subproduto_testavel',
            field=models.ForeignKey(verbose_name='Sub Produto Test\xe1vel', to='producao.SubProduto'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='linhasubprodutodoproduto',
            name='produto',
            field=models.ForeignKey(to='producao.ProdutoFinal'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='linhasubprodutodoproduto',
            name='subproduto',
            field=models.ForeignKey(to='producao.SubProduto'),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name='linhasubprodutodoproduto',
            unique_together=set([('produto', 'subproduto')]),
        ),
        migrations.AddField(
            model_name='linhasubprodutoagregado',
            name='subproduto_agregado',
            field=models.ForeignKey(related_name=b'linhasubprodutos_escolhidos', to='producao.SubProduto'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='linhasubprodutoagregado',
            name='subproduto_principal',
            field=models.ForeignKey(related_name=b'linhasubprodutos_agregados', to='producao.SubProduto'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='linhasubproduto',
            name='subproduto',
            field=models.ForeignKey(to='producao.SubProduto'),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name='linhafornecedorfabricantecomponente',
            unique_together=set([('componente', 'part_number_fornecedor', 'fornecedor')]),
        ),
        migrations.AddField(
            model_name='linhacomponenteavulsodoproduto',
            name='produto',
            field=models.ForeignKey(to='producao.ProdutoFinal'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='lancamentoprodproduto',
            name='nota_fiscal',
            field=models.ForeignKey(blank=True, to='producao.NotaFiscalLancamentosProducao', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='lancamentoprodproduto',
            name='ordem_de_producao',
            field=models.ForeignKey(blank=True, to='producao.OrdemProducaoProduto', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='lancamentoprodproduto',
            name='produto',
            field=models.ForeignKey(to='producao.ProdutoFinal'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='lancamentodefalhadeteste',
            name='subproduto',
            field=models.ForeignKey(to='producao.SubProduto'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='lancamentocomponente',
            name='nota',
            field=models.ForeignKey(to='producao.NotaFiscal'),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name='lancamentocomponente',
            unique_together=set([('part_number_fornecedor', 'nota'), ('part_number_fornecedor', 'componente', 'nota')]),
        ),
        migrations.AddField(
            model_name='followuprequisicaocompra',
            name='requisicao',
            field=models.ForeignKey(to='producao.RequisicaoDeCompra'),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name='falhadeteste',
            unique_together=set([('tipo', 'codigo')]),
        ),
        migrations.AddField(
            model_name='documentotecnicosubproduto',
            name='subproduto',
            field=models.ForeignKey(to='producao.SubProduto'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='documentotecnicoproduto',
            name='produto',
            field=models.ForeignKey(to='producao.ProdutoFinal'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='controledecompra',
            name='fornecedor',
            field=models.ForeignKey(blank=True, to='producao.FabricanteFornecedor', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='controledecompra',
            name='funcionario',
            field=models.ForeignKey(verbose_name='Funcion\xe1rio Respons\xe1vel', blank=True, to='rh.Funcionario', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='componente',
            name='tipo',
            field=models.ForeignKey(to='producao.ComponenteTipo'),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name='componente',
            unique_together=set([('identificador', 'tipo')]),
        ),
        migrations.AddField(
            model_name='atividadedecompra',
            name='controle_de_compra',
            field=models.ForeignKey(to='producao.ControleDeCompra'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='atividadedecompra',
            name='fechado_por',
            field=models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='arquivoanexocomponente',
            name='componente',
            field=models.ForeignKey(to='producao.Componente'),
            preserve_default=True,
        ),
    ]
